# Generated by Django 6.0.2 on 2026-03-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_paystac_976f7f_idx',
        ),
        migrations.RemoveField(
            model_name='escrowvault',
            name='transfer_notes',
        ),
        migrations.AddField(
            model_name='escrowvault',
            name='_transfer_notes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_oge',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_username',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('FUNDED', 'Payment Received — Funds Held'), ('PROVISIONED', 'Seller Uploaded Credentials'), ('INSPECTION', 'Buyer Verifying Credentials'), ('COMPLETED', 'Transaction Complete'), ('DISPUTED', 'Under Dispute — Funds Frozen'), ('CANCELLED', 'Cancelled / Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='escrowvault',
            table='escrow_vault',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystack_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystack_transfer_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='resolved_by',
        ),
    ]
