# Generated by Django 6.0.2 on 2026-03-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingvault_and_more'),
        ('orders', '0002_remove_order_orders_paystac_976f7f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowvault',
            name='_transfer_notes',
        ),
        migrations.AddField(
            model_name='escrowvault',
            name='transfer_notes',
            field=models.TextField(blank=True, help_text='Any transfer instructions'),
        ),
        migrations.AddField(
            model_name='order',
            name='funds_release_at',
            field=models.DateTimeField(blank=True, help_text='When seller funds are released to their balance. Set to now + ESCROW_HOLD_DAYS when buyer confirms. Celery task credits seller after this time.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_transfer_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_credited',
            field=models.BooleanField(db_index=True, default=False, help_text='False until the post-completion holding period expires and the Celery task credits seller_payout to total_earned.'),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_oge',
            field=models.BinaryField(db_column='oge_encrypted'),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_password',
            field=models.BinaryField(db_column='password_encrypted'),
        ),
        migrations.AlterField(
            model_name='escrowvault',
            name='_username',
            field=models.BinaryField(db_column='username_encrypted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('funded', 'Funded (Payment Received)'), ('in_provision', 'In Provision (Credentials Uploaded)'), ('disputed', 'Disputed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entry', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='platform',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paystack_reference'], name='orders_paystac_976f7f_idx'),
        ),
        migrations.AlterModelTable(
            name='escrowvault',
            table='escrow_vaults',
        ),
    ]
