# Generated by Django 6.0.2 on 2026-02-27 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('LISTING_CREATED', 'Listing Created'), ('LISTING_UPDATED', 'Listing Updated'), ('LISTING_PUBLISHED', 'Listing Published'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('LISTING_VIEWED', 'Listing Viewed'), ('ORDER_CREATED', 'Order Created'), ('ORDER_FUNDED', 'Order Funded'), ('ORDER_PROVISIONED', 'Credentials Uploaded'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_DISPUTED', 'Dispute Raised'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_REFUNDED', 'Order Refunded'), ('VAULT_VIEWED', 'Vault Credentials Viewed'), ('VAULT_UPLOADED', 'Vault Credentials Uploaded'), ('DISPUTE_RESOLVED', 'Dispute Resolved by Moderator'), ('USER_SUSPENDED', 'User Suspended'), ('USER_AUDITED', 'User Profile Audited'), ('PROFILE_UPDATED', 'Profile Updated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('ADMIN_ROUTE_ACCESS', 'Admin Route Accessed'), ('MOD_ROUTE_ACCESS', 'Moderator Route Accessed')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, help_text='Human-readable summary of the action.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, help_text="e.g. 'Order', 'Listing'", max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='UUID/PK of the related object', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='actlog_user_ts_idx'), models.Index(fields=['action', 'timestamp'], name='actlog_action_ts_idx'), models.Index(fields=['object_type', 'object_id'], name='actlog_obj_idx')],
            },
        ),
    ]
