# Generated by Django 6.0.2 on 2026-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Platform Owner'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], db_index=True, default='user', max_length=20),
        ),
    ]
