# Generated by Django 6.0.2 on 2026-03-06 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginactivity',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='bond_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bond_seized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_bond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reserved collateral slice of total_earned.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], db_index=True, default='user', max_length=20),
        ),
    ]
