# Generated by Django 6.0.2 on 2026-03-02 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage (e.g. 10.00 = 10%)', max_digits=5)),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=5000.0, help_text='Minimum seller withdrawal amount in Naira', max_digits=12)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Show maintenance page to all users')),
                ('disable_new_signups', models.BooleanField(default=False, help_text='Prevent new user registrations')),
                ('disable_new_listings', models.BooleanField(default=False, help_text='Prevent sellers from creating new listings')),
                ('disable_payments', models.BooleanField(default=False, help_text='Disable Paystack payment initiation')),
                ('support_email', models.EmailField(default='support@escrowmarket.com', max_length=254)),
                ('platform_name', models.CharField(default='EscrowMarket', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='withdrawal__seller__2d43f2_idx')],
            },
        ),
    ]
