# Generated by Django 6.0.2 on 2026-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='paystack_transfer_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='disable_new_listings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='disable_new_signups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='disable_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='min_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSING', 'Transfer Initiated'), ('APPROVED', 'Approved & Paid'), ('REJECTED', 'Rejected'), ('FAILED', 'Transfer Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
