# Generated by Django 6.0.2 on 2026-02-27 16:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('twitch', 'Twitch'), ('other', 'Other')], max_length=20)),
                ('account_handle', models.CharField(help_text='Public @handle', max_length=100)),
                ('account_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('average_engagement_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('account_age_months', models.PositiveIntegerField(default=0)),
                ('monthly_revenue_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('price_is_negotiable', models.BooleanField(default=False)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('analytics_screenshot', models.ImageField(blank=True, null=True, upload_to='analytics/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('under_review', 'Under Review'), ('sold', 'Sold'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'status'], name='account_lis_platfor_b2a4dc_idx'), models.Index(fields=['price'], name='account_lis_price_592562_idx'), models.Index(fields=['is_featured', 'status'], name='account_lis_is_feat_14a562_idx'), models.Index(fields=['status', 'created_at'], name='account_lis_status_c29726_idx')],
            },
        ),
    ]
