# Generated by Django 6.0.2 on 2026-03-06 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_username', models.BinaryField(db_column='username_encrypted')),
                ('_password', models.BinaryField(db_column='password_encrypted')),
                ('_oge', models.BinaryField(db_column='oge_encrypted')),
                ('transfer_notes', models.TextField(blank=True)),
                ('moderator_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listing_vaults',
            },
        ),
        migrations.RemoveField(
            model_name='accountlisting',
            name='price_is_negotiable',
        ),
        migrations.AddField(
            model_name='accountlisting',
            name='credential_failure_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive heartbeat failures. Auto-suspend triggers at HEARTBEAT_FAILURE_THRESHOLD (default 3).'),
        ),
        migrations.AddField(
            model_name='accountlisting',
            name='credential_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified ✓'), ('FAILED', 'Login Failed ✗'), ('CUSTODY_HELD', 'Platform Has Custody'), ('STALE', 'Re-verification Needed')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='accountlisting',
            name='custody_email',
            field=models.EmailField(blank=True, help_text='Platform-owned recovery email assigned to this account. Set by moderator during Level 1 custody onboarding.', max_length=254),
        ),
        migrations.AddField(
            model_name='accountlisting',
            name='custody_level',
            field=models.IntegerField(choices=[(0, 'No custody'), (1, 'OGE Email Custody'), (2, 'Pre-listed in Vault'), (3, 'Full Platform Custody')], default=0, help_text='How much control the platform holds over this account.'),
        ),
        migrations.AddField(
            model_name='accountlisting',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful credential heartbeat check.', null=True),
        ),
        migrations.AlterField(
            model_name='accountlisting',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('twitch', 'Twitch'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountlisting',
            index=models.Index(fields=['credential_status', 'status'], name='account_lis_credent_1e533b_idx'),
        ),
        migrations.AddField(
            model_name='listingvault',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_vault', to='listings.accountlisting'),
        ),
        migrations.AddField(
            model_name='listingvault',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_listing_vaults', to=settings.AUTH_USER_MODEL),
        ),
    ]
