# Generated by Django 6.0.2 on 2026-03-01 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_remove_order_orders_paystac_976f7f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('CREDENTIALS_INVALID', "Credentials Don't Work"), ('ACCOUNT_NOT_AS_DESC', 'Account Not As Described'), ('SELLER_UNRESPONSIVE', 'Seller Unresponsive'), ('WRONG_ACCOUNT', 'Wrong Account Delivered'), ('ACCOUNT_RECOVERED', 'Account Recovered by Original Owner'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Detailed explanation from the opener.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Moderator Review'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=20)),
                ('final_verdict', models.CharField(blank=True, choices=[('REFUNDED', 'Buyer Refunded'), ('RELEASED', 'Funds Released to Seller')], max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_mod_note', models.BooleanField(default=False, help_text='True when posted by a Moderator — shown with special styling.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='dispute_evidence/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_evidence',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='disputes_status_536461_idx'),
        ),
    ]
