# Generated by Django 6.0.2 on 2026-03-02 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID for conversion tracking', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='storefront.store')),
            ],
            options={
                'db_table': 'store_page_views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['store', 'timestamp'], name='store_page__store_i_093ae0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_clicks', to='storefront.store')),
            ],
            options={
                'db_table': 'store_button_clicks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['store', 'timestamp'], name='store_butto_store_i_7e762a_idx')],
            },
        ),
    ]
