# Generated by Django 6.0.2 on 2026-03-01 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_583549_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_2c3905_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('SALE_MADE', 'Sale Made'), ('CREDENTIALS_UPLOADED', 'Credentials Uploaded'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_DISPUTED', 'Order Disputed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('DISPUTE_OPENED', 'Dispute Opened'), ('DISPUTE_MESSAGE', 'New Dispute Message'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('LISTING_APPROVED', 'Listing Approved'), ('LISTING_REJECTED', 'Listing Rejected'), ('LOGIN_ALERT', 'New Login Alert'), ('SYSTEM', 'System Notification')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'),
        ),
    ]
